### ISSUE TITLE
New FilterOperator: alphanum, to put alpha-numeric before non alpha-numeric

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1402]
In our lists we see how titles starting with e.g $ or " get priority above alpha-numeric characters. Example:

![filteroperator_alphanum](https://cloud.githubusercontent.com/assets/4534056/5835481/93819230-a169-11e4-99f7-ab2f1b554aca.PNG)

Another example is that we get "system titles above content titles" in mixed lists where it probably is desired to see the content titles first.

I propose two new FilterOperator, titled alphanum and alphanumcs to change this order so that alphanumerical characters get highest priority. the -cs is for case sensitive.

String values are sorted case sensitively (upper and lower case letters are considered different). Preceding the operator with ! reverses the sort order.

We may wish to consider some particular exceptions (based on human psychology). In the lists on tw.com it is obvious that titles within quotes `".."` are content. Maybe there should be also *alphanumx* and *alphanumcsx* (*-x* or *-ex* for *exception*) that yields the following:

>"A Thesis Notebook" by Alberto Molina
About
...[ snip ]...
BootMechanism
"BrainTest - tools for a digital brain" by Danielo Rodriguez
BrowserCompatibility
...

There may be other such exceptional characters, e.g @, #, (, [ or even string `[[`

*Alternatively:*

...insteadf of defining exceptional characters, there may be a special "indicator" to instruct the filter that this title, in deed, should be placed at it's numerically evaluated value (or however order is calculated). For instance it may be desired to get title `$100 for a laptop´ or ´§ Righs of Man´ at top. The "indicator" could be a very uncommon character at start of title to differentiate these items, but this character should probably be hidden from view everywhere but in tiddler edit view. (A bit like ~ is hidden from view in some cases.)

**Comment by tobibeer** [comment]
Maybe that's not a filteroperator by its own but a default... as I may want to combine it with other sort preferences, e.g. #1399.

**Comment by twMat** [comment]
@tobibeer I had not seen #1399 when I posted this. If the two are in conflict, please feel free to extract what you find usable here and I will close this thread.

`[sort:option:option:option[field]]`

Superior! One question is if the "!" would still be usable because it would not be clear which option it refers to. Maybe this would be speciefied per individual option?

`[sort:!option:!option:option[field]]`

**Comment by tobibeer** [comment]
Negation would, of course, in general always apply to the entire filter run, e.g.

[!sort:option:option:option[field]]

As for negating individual options, I really don't think that is needed because not declaring any option should generally default to not doing that.

A more important question is perhaps in which sequence certain options are combined. I think that needs to be hard-coded. For example "make tiddlers starting with **foo** first" (#1399) would outplay "sort numerically" ([nsort](http://tiddlywiki.com/#FilterOperator%3A%20nsort), [nsortcs](http://tiddlywiki.com/#FilterOperator%3A%20nsortcs)). Perhaps the order in which the options are declared might declare the domininance in which they are applied.

**Comment by aelocson** [comment]
See also #1410.

I agree that having separate operators for these options is wrong. If nothing else, it make the operator names clumsy.

For flexibility, it would be nice if the options could be specified via variables or transclusions:

`[sort:<option>:{options}[field]]`

**Comment by pmario** [comment]
imo can be achieved with: http://tiddlywiki.com/#Filter%20Operators:%5B%5BFilter%20Operators%5D%5D%20%5B%5Bnsort%20Operator%5D%5D%20%5B%5Bnsort%20Operator%20(Examples)%5D%5D%20%24%3A%2FAdvancedSearch

so issue may be closed?

**Comment by tobibeer** [comment]
@pmario: how?

This doesn't look like it does what it should:

![nsort](https://user-images.githubusercontent.com/97566/33469901-c15ab5c2-d665-11e7-9dbf-567b7dacd6fa.jpg)

```
{{{ [all[]nsort[limit[100]] }}}
```

Also, I do believe the underlying request ask for there to be a filter to do complex sorts with a single sort filter, not sequentially chained simple sorts in one run.

**Comment by pmario** [comment]
IMO `{{{ [all[]nsortcs[]limit[100]] }}}` or 
`{{{ [all[]nsortcs[]limit[100]] -[is[system]] }}}` does work

I still think, this doesn't need new operators. ... Special chars can be filtered with `[prefix[§]]` ... and so on.

**Comment by tobibeer** [comment]
@pmario, sry, I had a typo in my filter.

However, I don't see how the OP can be achieved through any of that w/o creating an immensely complex filter expression.

**Comment by Jermolene** [comment]
I think that we'd need to incorporate an off-the-shelf JS library for this? Isn't it locale sensitive, too? Again, I think it's maybe plugin territory?

**Comment by joshuafontany** [comment]
I have run into this same issue when using my "Json Mangler" plugin. The
keys of a "flat JSON object" are XPath-like strings, such as:

"field[0].@name" : "zero",
"field[1].@name" : "one",
"field[2].@name" : "two",
"field[3].@name" : "three",
"field[10].@name" : "ten"

But the JS sort I used ends up "alphabetically" sorting this to:

"field[0].@name" : "zero",
"field[1].@name" : "one",
"field[10].@name" : "ten",
"field[2].@name" : "two",
"field[3].@name" : "three"

I just started researching this, but here is a good resource:

http://www.davekoelle.com/alphanum.html


Best,
Joshua Fontany

**Comment by pmario** [comment]
@twMat ... IMO this https://tiddlywiki.com/#sortan%20Operator:%5B%5Bsortan%20Operator%5D%5D%20%5B%5Bsortan%20Operator%20(Examples)%5D%5D should fix the issue. please check!

**Comment by twMat** [comment]
@pmario I still don't understand how I would get these results:

```
aaa bbb $:/aaa $:/bbb  ----- i.e system/shadow tids last but still alphabetical order

aaa bbb "aaa" "bbb" ---- same as above

aaa "bbb" ccc   ---- integrated order  
```

**Comment by pmario** [comment]
So you basically want: 1 2 3 IV V to be sorted in the right, way, where IV and V are roman numbers. 

`aaa` and `"aaa"` are fundamentally different different strings. `aaa` has 3 characters and `"aaa"` has 5. 

Sorting them in an arbitrary order is highly usecase specific. 

Every alphabetical sort algorithm uses an ASCII table or the 2 byte unicode representation thereof, to create the sort order. see: https://en.wikipedia.org/wiki/ASCII#Printable_characters ... 

So `"` has a lower value then `a` and that's why it comes first. .. If you don't want the quote `"` to influence the sort order ... you have to avoid it. ... 

You have to think about 1 very important thing here. Our character set is very limited. [There are other character sets](https://unicode-table.com), that use a 100 times more different chararcters, and the sorting algorithm still has to make sense. ... 

Limiting the sort algorithms to our convenience doesn's solve problems. .. IMO It creates them.
