### ISSUE TITLE
Invisible icons in advanced search in few themes

### ISSUE THREAD

**Issue by cbhushan** [Jermolene/TiddlyWiki5#1787]
Some icons next to the search bar in advanced search is not visible in some of the themes/palettes. An example is shown below - icons are visible in vanilla but not in contrast. Using version 5.1.8

I am guessing it has to do with some CSS settings. I never noticed the export button in advanced button because of this. 

![vanilla](https://cloud.githubusercontent.com/assets/3436053/8095012/ab2f1450-0f7f-11e5-8fe6-c2fb48d1cc62.png)
![contrast](https://cloud.githubusercontent.com/assets/3436053/8095013/ab314784-0f7f-11e5-8734-1d8ecd025821.png)

**Comment by Jermolene** [comment]
Thanks @cbhushan this is actually already fixed in the prerelease of 5.1.9:

http://tiddlywiki.com/prerelease

**Comment by cbhushan** [comment]
May be I am doing something wrong, but I am still seeing this in release 5.1.9. Using Firefox 38.0 on Linux Mint 17.1 with Mate 1.8.1. Steps to reproduce: 

1. Navigate to http://tiddlywiki.com/
2. Open control-panel > Appearance > Palette. Select Blue theme. 
3. Go to advanced-search > Filter. Enter `[tag[About]]` in search bar. No icons are visible next to search bar.
4. Change to default 'Vanilla' theme and icons are now visible. No icons are visible for following themes: Blue, Rocker and DarkPhotos.

**Comment by Jermolene** [comment]
Thanks @cbhushan. For 5.1.9 I was focussing on the contrast themes, I'll review the others for 5.1.10
