### ISSUE TITLE
extend list filter operator to retrieve list(s) for input title(s)

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2598]
Extend the list filter to allow using it as follows:

For all input titles, retrieves the titles in the default **list** field:

```
[[sometitle]list[]]
```

For all input titles, retrieves the titles in the list-field **foo**:

```
[[sometitle]list:foo[]]
```

**Comment by Jermolene** [comment]
Hi @tobibeer funnily enough just yesterday I needed a filter operator that retrieved all the tiddlers listed in the list field of the current result list. I implemented it as a separate "getlist" operator: https://gist.github.com/Jermolene/85d245a8d3aec60f660fc06920ad892e

Your idea of changing the behaviour of the `list` operator when the operand is missing is neat, but it complicates the semantics and makes them inconsistent with other operators. Hence my preference for a wholly new filter operator.

**Comment by tobibeer** [comment]
I've always felt that the list filter is confusing in how it doesn't allow you to retrieve the list of the input titles. I'd rather we "overload" it, or rather, have it do what one would reasonably expect it to do.

But whatever you prefer.

**Comment by tobibeer** [comment]
At least from a parameterization point of view, things are neatly separated in that we still have the case where we define any operand to specify a list to be retrieved. Meaning: no suffix would change that.

**Comment by danielo515** [comment]
I feel that @tobibeer solution is cleaner. Most of the operators accept an item as input, but the list does not. I found myself falling in that trap several times. Having a separate filter operator for doing a task that is expected to be on another operator is confusing for me and I probably get frustrated before I thing about looking for another operator. The current number of operators is big enough, I vote for keeping it as small as possible.

**Comment by tobibeer** [comment]
Here's a demo for my proposal for all the considerations above:

http://2598.tiddlyspot.com

And a gist for commenting:

https://gist.github.com/tobibeer/5e13e5288d79a6db5226d6f7af09626a

**Comment by Jermolene** [comment]
Hi @danielo515 I think the current `list` operator is pretty much broken, because it's so inconsistent with other operators. The advantage of fixing it with one or more new operators is that then we can deprecate the existing `list` operator. Subsequently, new people learning TiddlyWiki would no longer need to encounter the inconsistency. Alternatively, overloading the existing operator adds to the complexity of learning TiddlyWiki for all time.

**Comment by tobibeer** [comment]
@Jermolene, rather than deprecate an entire filter, especially one that is of core importance, I think we should deprecate (that is "not recommend") the old way of using it, while allowing people to use it the way now suggested.

Am I naive to think that the performance impact of overloading it like that is rather minimal?

To me, having two filter and having to learn that one is not recommended / deprecated adds more to the learning curve than overloading and still mentioning the old ways it was used before.

**Comment by inmysocks** [comment]
I have never liked the name of the list operator, so I think that adding one with a new name is a good idea.

**Comment by saqimtiaz** [comment]
With the addition of the `enlist-input` operator this can be closed @Jermolene

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
