### ISSUE TITLE
No refresh from action-setfield in Firefox

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4472]
As discovered [here](https://groups.google.com/d/msg/tiddlywiki/5Z_TwiVk8ls/i5olk13BAQAJ), it seems `action-setfield` does not refresh the tiddler editview in Firefox. It does work in e.g Chrome.

The problems seems to happen on **tiddlywiki.com but not on prerelease**!

**To replicate**
In Firefox, go to https://tiddlywiki.com/
Create a tiddler with this content named e.g "test"

```
title: NOT New Tiddler
<$button>
  clicking this should set editor text to "foo" in //Draft of 'New Tiddler'//
   <$action-setfield $tiddler="Draft of 'New Tiddler'" text="foo"/>
</$button>
```
Now create a second new tiddler (i.e titled "New Tiddler") keep it empty and **leave it open in edit mode**.

Clicking the button should set the *Draft of 'New Tiddler'* editor to read "foo". This **works** but only the first time (virgin state). Replacing the *foo* with *asdf* and clicking again does not give result.... unless you also make a "manual refresh", such as from rearranging the titles by DnD in the Open sidebar tab.

**Comment by Jermolene** [comment]
Hi @twMat I can't duplicate this on Firefox on the Mac; setting the text works reliably for me. There is a delay after pressing the button before the text appears, of course, because of the way we throttle refreshes of draft tiddlers.

**Comment by twMat** [comment]
@Jermolene - thank you very much for looking at it. It seems I am mistaken - the above MTC does work on FF! I will try to reshape a new MTC to illustrate it. Sorry for my mistake.

**Comment by twMat** [comment]
Closing while fiddling.

**Comment by twMat** [comment]
@Jermolene 

OK, I've updated the OP in this thread with new instructions. It seems there is a difference between current version of TW and prerelease so maybe it is a side effect from a known issue? Please see if you can replicate it.

**Comment by twMat** [comment]
Could someone confirm this, please?
And, if confirmed as a problem in v5.1.21 but already sufficiently dealt with in 5.1.22... should I then close this issue?

**Comment by Jermolene** [comment]
Hi @twMat I can confirm that I can duplicate this now, and have been investigating. It's a problem with the refreshing of the edit-text widget, but it's really super strange to find a browser-specific bug, and I'm none the wiser at present.

**Comment by Jermolene** [comment]
> The problems seems to happen on tiddlywiki.com but not on prerelease!

I think the issue might be whether your using the CodeMirror plugin. https://tiddlywiki.com/prerelease/ has the CodeMirror plugin. If you test with https://tiddlywiki.com/empty.html (which doesn't have the plugin), you'll see the problem is still present in v5.1.22

**Comment by Jermolene** [comment]
cc @BurningTreeC -- this is one of the issues we were discussing last weekend

**Comment by twMat** [comment]
>If you test with https://tiddlywiki.com/empty.html (which doesn't have the plugin), you'll see the problem is still present in v5.1.22

Annoying.

I doubt the following has anything to do with it but who knows: As noted, the "foo" does appear when manually DnD'ing the titles in the sidebar Open tab. However, it does not work if one DnD's the edited tiddler. The "foo" only appears if it is some *other* tiddler being DnD'ed. My point is that maybe it is easier to track down why it doesn't refresh in one of the scenarios when the two very similar scenarios can be put side by side.
...or maybe refresh from DnD is a whole other matter.

Is there any (wikitext) command to force refresh?

BTW, why did you close this issue?

**Comment by Jermolene** [comment]
Hi @twMat because I pushed a fix in the commit mentioned above, you should be able to try it out at https://tiddlywiki.com/empty.html now

**Comment by twMat** [comment]
Thanks - but it is still the same problem when I try it on /empty. Win10, FF.

**Comment by Jermolene** [comment]
Sorry I meant to say that the fix is on https://tiddlywiki.com/prerelease/empty.html

**Comment by twMat** [comment]
Yay!!! Thank you!

**Comment by twMat** [comment]
@Jermolene - [reopen](https://github.com/Jermolene/TiddlyWiki5/commit/a6f6db40d9b894370653fb44ff5ab8fe798e4d53)?
