### ISSUE TITLE
[BUG] Internal JS error in 5.1.23 and xlsx-utils ?

### ISSUE THREAD

**Issue by silvyn** [Jermolene/TiddlyWiki5#5400]
**Describe the bug**

Hi,

Today we found that XLSX-Utils doesn't work with version 5.1.23

**To Reproduce**
1. Go to 
https://tiddlywiki.com/prerelease/editions/xlsx-utils/
2. Try to import XLSX demo
3. See red alert Internal Javascript Error

(on 5.1.24 pre-release, maybe the type error is different TypeError: this.wiki is undefined from a 5.1.23, but both are red screen of the death.

**Comment by silvyn** [comment]
Test with 5.1.22, almost work, just notice yellow alert like "Missing title field for {"title":"","text":"","role":"state","tags":["States"]}" but import is OK.

**Comment by Jermolene** [comment]
Thanks @silvyn I've fixed the crash, and am now investigating the "Missing title field" problem.

**Comment by Jermolene** [comment]
Hi @silvyn I think the "Missing title field" problem was actually some issues with the demo spreadsheet. I've updated it in ae273a08f138dc470cb034cdc9867bb6defc2323, which should be live at https://tiddlywiki.com/prerelease/editions/xlsx-utils/ shortly.

**Comment by fazoni** [comment]
### Still getting the Error when trying the XLSX Utilities Plugin "Presidents Demo".

@Jermolene, notwithstandig your [actions](https://github.com/Jermolene/TiddlyWiki5/issues/5400#issuecomment-761588989) there still seems to be an issue.

To reproduce, use the [above mentioned instructions](https://github.com/Jermolene/TiddlyWiki5/issues/5400#issue-785391448) by @silvyn.

**Error** message received in:
- **Google Chrome 91.0.4472.77** 
```
xlsx-utils - 10th June 2021 at 1:48pm (count: 949)
Missing title field for {"title":"","text":"","role":"state","tags":["States"]}

```
```
xlsx-utils - 10th June 2021 at 1:48pm
Missing title field for {"title":"","text":"was born in and was in office March 4, 1893 – March 4, 1897","role":"president","tags":[""]}

```
```
xlsx-utils - 10th June 2021 at 1:48pm (count: 723)
Missing title field for {"title":"","text":"","role":"justice","tags":[""],"trivia":""}

```
- **Firefox 89.0**

```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: this.wiki is undefined
```

- **Opera 76.0.4017.154**
```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught TypeError: Cannot read property 'getTiddlerText' of undefined
```

Any hope to get this fixed? This looks really promising.
I am newbie to [Tiddlywiki](https://tiddlywiki.com), is there another way to batch create tiddlers from external structured data?

Thanks in advance.
