### ISSUE TITLE
[IDEA] Re-implement modals in WikiText

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7267]
It was suggested by one @Jermolene that it might be prudent to re-engineer TW modals, preferrably in WikiText.

I have tried to create a baseline version (posted as a PR shortly) that implements all the documented functionality (except for `rootwindow`). I'll write about the limitations and differences to the current modals in the PR, to make that a bit self-contained.

Feel free to play around with the preview and offer improvements.

Also, since the message handling is written in WikiText, too, I have not found a great way to transfer the hashmap of parameters to variables inside the modal. Currently, I'm using `$setmultiplefields` to put them into temporary tiddlers, and then `$setmultiplevariables` to assign the indexes to modal variables. The latter handling of `tm-modal` in JS will probably take care of this, I hope.

**Comment by saqimtiaz** [comment]
It is worth considering that the current JavaScript based implementation of modals offers certain advantages over a wikitext based approach:

* modals cannot be bricked by changing the page template and its components, offering a safe means to switch layouts
* since modals are controlled via JavaScript, they can be used to implement progress bars for long running tasks such as rendering static sites, that would not be possible with wikitext.

As such, it might be worth considering a new wikitext based mechanism for modals that might co-exist alongside the current implementation. This would also alleviate the need to maintain strict backwards compatibility.

There may also be some overlap here with a revamp of the notification mechanism to allow multiple stacking notifications, including notifications that need to be explicitly closed.

**Comment by yaisog** [comment]
> As such, it might be worth considering a new wikitext based mechanism for modals that might co-exist alongside the current implementation.

I'd prefer a separate mechanism for non-standard usage of modals, e.g. for layout switching or JavaScript injection.
Modals that do the things which are documented on tiddlywiki.com should be very well implementable in WikiText. Maybe I'd be a good idea to call them "WikiModals" for now and develop them alongside the originals as you propose – this way it is easier to put them into a plugin later, should they never make it into the core.

They would be called via a `tm-wikimodal` message for now. Or I'd make a custom `$action-wikimodal` widget, to get rid of the otherwise necessary `$messagecatcher` in the PageTemplate.

I'll happily leave the fight over general architecture concerns to @Jermolene, though.

**Comment by yaisog** [comment]
I pushed a major overhaul to the PR, which incorporates many of the suggestions so far and coexists with the previous implementation.
For more details, see [this comment in the PR](https://github.com/Jermolene/TiddlyWiki5/pull/7268#issuecomment-1438360819).

**Comment by pmario** [comment]
@yaisog ... You closed the related PR. So is the issue still valid?

**Comment by yaisog** [comment]
Hi @pmario thanks for following up. While there is probably general agreement that modals should be updated, there seems to be little interest in doing so. I don't think we need to keep this issue open just to remind us of it.
I have a working solution in my wiki that is loosely based on the PR, but optimized for my personal use cases. So I have no pressing need at the moment. If I ever continue work on this, I'll open a new issue.
