### ISSUE TITLE
[BUG] nodejs build fails with message ""Global assignment is not allowed within modules on node.""

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#7465]
### Describe the bug

this has to do with https://github.com/Jermolene/TiddlyWiki5/pull/4624

'globalThis' is not defined in nodejs until version 12. ubuntu is still on version 10

I suggest adding something like this to the boot:

```
var nodeMajorVersion = Number(((process.version).split(".")[0]).slice(1));

$tw.utils.evalSandboxed(moduleInfo.definition,sandbox,tiddler.fields.title,(nodeMajorVersion < 12));
```

### TiddlyWiki Configuration

prerelease 5.3.0

**Comment by buggyj** [comment]
the code needs a guard for nodejs only

```
var nodeMajorVersion;
if ($tw.node) nodeMajorVersion = Number(((process.version).split(".")[0]).slice(1));
```

**Comment by pmario** [comment]
The latest Node.js LTS version is 18 .. So I think we should _not_ change anything in TW to maintain compatibility for Node 10 or even 12. Both of them are "dead" -> **Not maintained and therefore highly unsecure**. https://en.wikipedia.org/wiki/Node.js

There is no problem to update Node versions in ubuntu. So you should use a newer version

**Comment by rmunn** [comment]
In fact, Node 20 just came out last month: https://nodejs.org/en/blog/announcements/v20-release-announce

I do agree with adding a check for the Node version, and refusing to run if it's too low (perhaps with a link to https://github.com/nodejs/release or https://nodejs.org/en/download/current or something). According to the chart at https://github.com/nodejs/release, Node 14 is just about to fall out of Maintenance mode, so by the time TW 5.3.0 releases, the earliest supported version of Node will be 16.

**Comment by buggyj** [comment]
There will be tens of million of people running older versions of node - that is their choice. Many will not have permission to upgrade their computer installation or will be unwilling or unable to do it. I do not believe that tiddlywiki should police which versions of node it will run with - it did not do it in the past.

On a related note: I believe that the checking 'globalThis' should be configurable as there may be third party nodejs modules that will fail to run as they modify the globalThis.

**Comment by Jermolene** [comment]
Thanks @buggyj – please could you make a PR with the changes you propose?

I do not think TW should fail with an error if running on an old version of Node.js, for the reasons that @buggyj mentions.  The wider points about baseline compatibility should be part of the ongoing discussions in #7353 about bumping the JS dialect we target.

**Comment by buggyj** [comment]
I would need to have a closer look at the code. Maybe @Arlen22 would like to comment.

**Comment by Arlen22** [comment]
@buggyj, Please test this branch for me and let me know if it fixes the issue. The polyfill was explicitly supposed to work with Node 0.10, so that is definitely a bug. This should fix the issue. 

https://github.com/Jermolene/TiddlyWiki5/pull/7478

**Comment by buggyj** [comment]
@Arlen22 I tried your pull request,  unfortunately this issue persists

**Comment by Arlen22** [comment]
@buggyj, I'm starting to get slightly confused. I was looking at this on the fly and made an assumption about the error you're getting. I just downloaded node 0.10 and 0.12 and neither of them throw an error on the line `if (typeof globalThis === "object")`. What is the actual error here?

**Comment by Arlen22** [comment]
Ok, I did some additional testing on Node 0.10.48. First of all, your comment [in the other PR](https://github.com/Jermolene/TiddlyWiki5/pull/7478#issuecomment-1559208172) about globalThis being enumerable is correct. Thankfully the globalThis implementation in browsers and node set enumerable to false, so I will change that. 

Secondly, I discovered that this kind of checking is overkill for our typical purposes because the global variable is not even defined for modules run with evalSandboxed, so they would probably have to use the same hack as the polyfill does to make the changes in the first place. globalThis is not supposed to be defined either, so I'm going to change that.

**Comment by Arlen22** [comment]
Please test this and let me know if it solves the issue: https://github.com/Jermolene/TiddlyWiki5/pull/7492

**Comment by buggyj** [comment]
Hi @Arlen22, I am now able to build again with this change, so it fixes this issue. @Jermolene

**Comment by flibbles** [comment]
Did that PR go in with v5.3.0, because I'm no longer able to run Relink tests for this very reason on that version release.

**Comment by pmario** [comment]
If you mean PR https://github.com/Jermolene/TiddlyWiki5/pull/4624  -- it has been merged. 
IMO you may open a new issue and reference the PR.

**Comment by pmario** [comment]
@buggyj -- Has this issue been resolved?

**Comment by flibbles** [comment]
Very well. I opened #7585.

**Comment by buggyj** [comment]
I not longer see this problem
