### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shadowrevenant** [Jermolene/TiddlyWiki5#7777]
### Describe the bug

Multiple Empty Transclusions Freezes/ Hard Crashes TW5

When adding 2 or more {{}} Transclusions with no data any time the Tiddler is visible tiddlywiki completely freezes and depending on the browser, will register as crashed no TW5 Js Error popup just Instantly Freezes

### Expected behavior

Multiple Transclusion errors, continued function 

### To Reproduce

1. Open Tiddly Wiki
2. Create a new Tiddler 
3. Enable Preview (faster but optional)
4. Type {{}}{{}}

### Screenshots

![SmartSelect_20231007-085718_Tiddloid](https://github.com/Jermolene/TiddlyWiki5/assets/114278197/4d7e4137-fa6c-4cf0-8af3-3d20ccf3d967)

### TiddlyWiki Configuration

- Version [v5.3.1]
- Saving mechanism [WebDAV, Browser, Tiddloid]
- Plugins installed [None]

### Desktop (please complete the following information):

- OS: [Windows 11]
- Browser [chrome, edge, palemoon, operaGX]
- Version [Latest]

### Smartphone (please complete the following information):

- Device: [Galaxy Note 8]
- OS: [Android]
- Browser [stock browser(Samsung)]
- Version [Latest]

### Additional context

This has been done everywhere from my phone/pc with webdav/default empty/www.tiddlywiki.com. the issue occurs the same regardless of the browser, and if saved that Tiddler will always crash tw5 when opened

**Comment by kookma** [comment]
I can also confirm this in TW 5.3.2p.

**Comment by pmario** [comment]
IMO that's a duplicate from issue  **[BUG] Problem with empty transclusions #7767**  which should be solved once ** Ensure {{}} doesn't cause a recursion error #7768 ** is merged

**Comment by Jermolene** [comment]
Thanks @shadowrevenant I've merged #7768 which fixes this problem. You can test it at https://tiddlywiki.com/prerelease

**Comment by shadowrevenant** [comment]
Issue Still (Sorta) Exists,
Go to Pre 5.3.2, Create New Tiddler, Create {{New Tiddler}} {{New Tiddler}} 
Then STOP, HAMMER TIME. Freezes again, In Prior Versions there would be a transclusion error that you are trying to transclude the src tiddler this just freezes 

NOTE:
This issue doesn't occur in preview for some reason, but does when you commit/save changes to the tiddler

**Comment by kookma** [comment]
> NOTE:
> This issue doesn't occur in preview for some reason, but does when you commit/save changes to the tiddler.

I confirm this in TW 5.3.2p. The preview pan works fine, but when saving as you stated, the recursion error is occurred.

**Comment by Jermolene** [comment]
Hi @shadowrevenant @kookma that example with `{{New Tiddler}}` is a more straightforward explicit recursion error. The reason it doesn't occur in the preview is because at that point the tiddler "New Tiddler" hasn't actually been created.

**Comment by Jermolene** [comment]
The reason why `{{New Tiddler}} {{New Tiddler}}` goes into an infinite loop while `{{New Tiddler}}` correctly results in an recursion error is interesting.

In the latter case, the recursive transclusion happens 1,000 times and then the recursion is detected once the widget tree depth exceeds that limit. In the former case, each level of recursion yields double the number of child transclusions. That means that there would be 2^1000 leaf nodes if the process was allowed to continue.

This provides further evidence that widget tree depth is not a robust way to detect recursion. We probably need to employ multiple defences at the same time.
